import type { NextPage } from 'next'
import React, { useMemo , useEffect , useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from 'react-redux'
import { getContent } from '../storeData/getContent'
import type { RootState } from '../store'
import axios from 'axios';
import CustomTable from '../component/CustomTable';
import BasicTable from '../component/BasicTable';
import GroupTable from '../component/GroupTable';
import SortingTable from '../component/SortingTable';
import FilteringTable from '../component/FilteringTable';
import PaginationTable from '../component/PaginationTable';
import RowSelectionTable from '../component/RowSelectionTable';
import ColumnOrderTable from '../component/ColumnOrderTable';
import HidingColumnTable from '../component/ColumnHidingTable';
import Table from '../component/Table';
import Pagination from '../component/Pagination'
import ModalImage from 'react-modal-image';
import { useMediaQuery } from 'react-responsive';


const Home: NextPage = () => {

  const [data, setData] = useState([]);
  // const [loading, setLoading] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [dataPerPage, setDataPerPage] = useState(10);

  const isMobile = useMediaQuery({ query: `(max-width: 600px)` });
  
  // Using useEffect to call the API once mounted and set the data
    useEffect(() => {
      (async () => {
        const result = await axios("http://jsonplaceholder.typicode.com/photos");
        setData(result.data);
      })();
    }, []);

    const columns = useMemo(
      () => [
        {
          Header: 'id',
          accessor: 'id'
        },
        {
          Header: 'title',
          accessor: 'title',
        },
        {
          Header: 'thumbnail',
          accessor: 'thumbnailUrl',
          Cell: ({ cell: { value } }) => {
            return <ModalImage
            small={value}
            large={value}
            alt="Modal"
          />
          }
        },
      ],
      []
    );

    const columnMobile = useMemo(
      () => [
        {
          Header: 'id',
          accessor: 'id'
        },
        {
          Header: 'title',
          accessor: 'title',
        },
      ],
      [
        {
          Header: 'thumbnail',
          accessor: 'thumbnailUrl',
          colSpan: 2,
          Cell: ({ cell: { value } }) => {
            return <ModalImage
            small={value}
            large={value}
            alt="Modal"
          />
          }
        },
      ]
    );


    // Get current data
    const indexOfLastData = currentPage * dataPerPage;
    // console.log(indexOfLastData);
    const indexOfFirstData = indexOfLastData - dataPerPage;
    // console.log(indexOfFirstData);
    const currentData = data.slice(indexOfFirstData , indexOfLastData);
    // console.log(currentPage);
    const rangePage = 10;

    //Change Page
    const paginate = pageNumber => setCurrentPage(pageNumber);

  return (
    
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          {/* <CustomTable/> */}
          <div className={styles.container}>
            <h1>Custom Table</h1>
            <h2>Current Page : {currentPage}</h2>
            <div className="App">
              {!isMobile ? <Table columns={columns} data={currentData} /> : <Table columns={columnMobile} data={currentData} /> }
            </div>
            <Pagination dataPerPage={dataPerPage} totalData={data.length} paginate={paginate} currentPage={currentPage} rangePage={rangePage} />
            {/* <BasicTable /> */}
            {/* <GroupTable /> */}
            {/* <SortingTable /> */}
            {/* <FilteringTable /> */}
            {/* <PaginationTable /> */}
            {/* <RowSelectionTable /> */}
            {/* <ColumnOrderTable /> */}
            {/* <HidingColumnTable /> */}
          </div>
          
      </main>

      
    </div>
  )
}

export default Home
