import type { NextPage } from 'next'
import React, { useMemo , useEffect , useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from 'react-redux'
import { getContent } from '../storeData/getContent'
import type { RootState } from '../store'
import axios from 'axios';
import CustomTable from '../component/CustomTable';
import BasicTable from '../component/BasicTable';
import GroupTable from '../component/GroupTable';
import SortingTable from '../component/SortingTable';
import FilteringTable from '../component/FilteringTable';
import PaginationTable from '../component/PaginationTable';
import RowSelectionTable from '../component/RowSelectionTable';
import ColumnOrderTable from '../component/ColumnOrderTable';
import HidingColumnTable from '../component/ColumnHidingTable';
import Table from '../component/Table';


const Home: NextPage = () => {

  const [data, setData] = useState([]);
  
  // Using useEffect to call the API once mounted and set the data
    useEffect(() => {
      (async () => {
        const result = await axios("http://jsonplaceholder.typicode.com/photos");
        setData(result.data);
      })();
    }, []);
    

    const columns = useMemo(
      () => [
        {
          Header: 'id',
          accessor: 'id',
          // Footer: 'Id',
          // Filter: ColumnFilter,
          disableFilters: true
        },
        {
          Header: 'title',
          accessor: 'title',
          // Footer: 'First Name'
          // Filter: ColumnFilter
        },
        {
          Header: 'thumbnail',
          accessor: 'thumbnailUrl',
          Cell: ({ cell: { value } }) => {
            return <div><img height={60} src={value}/></div>
          }
          // Cell: columns => <img src={} />
        },
          // Footer: 'Last Name'
          // Filter: ColumnFilter
      ],
      []
    );

  return (
    
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          {/* <CustomTable/> */}
          <div className={styles.container}>
            <h1>Custom Table</h1>
            <div className="App">
              <Table columns={columns} data={data} />
            </div>
            {/* <BasicTable /> */}
            {/* <GroupTable /> */}
            {/* <SortingTable /> */}
            {/* <FilteringTable /> */}
            {/* <PaginationTable /> */}
            {/* <RowSelectionTable /> */}
            {/* <ColumnOrderTable /> */}
            {/* <HidingColumnTable /> */}
          </div>
          
      </main>

      
    </div>
  )
}

export default Home
